enum JWT_TOKEN_TYPES {
    ACCESS_TOKEN = "ACCESS_TOKEN",
    PRE_LOGIN_TOKEN = "PRE_LOGIN_TOKEN",
    CAPTCHA_TOKEN = "CAPTCHA_TOKEN",
    DEVICE_TOTP_SETUP_TOKEN = "DEVICE_TOTP_SETUP_TOKEN",
}

export {
    JWT_TOKEN_TYPES
}
